name: dart_qv
version: 0.0.1
description: Interface for QlikSense Engine API
author: Vadim Tsushko <vadimtsushko@gmail.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  logging: any
  quiver_log: any
  browser: any
  websockets: any
  json_rpc_2: any
  web_socket_channel: any
  stream_channel: any
  unscripted: any
  http: '>=0.11.3+7'
  inqlik_cli:
    path: ../inqlik_cli
dev_dependencies:
  test: '^0.12.13+4'
